/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_v1_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/parse-resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Resume */
        post: operations["parse_resume_api_v1_profiles_parse_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profiles__profile_id__get"];
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_v1_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_profiles__profile_id__patch"];
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/resume.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Profile Resume Pdf */
        get: operations["export_profile_resume_pdf_api_v1_profiles__profile_id__resume_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/apply-resume-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Resume Suggestions */
        post: operations["apply_resume_suggestions_api_v1_profiles__profile_id__apply_resume_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/parse-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Job Text */
        post: operations["parse_job_text_api_v1_jobs_parse_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /** Update Job */
        patch: operations["update_job_api_v1_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/company-research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Company Research */
        post: operations["create_company_research_api_v1_jobs__job_id__company_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Match Analyses */
        get: operations["list_match_analyses_api_v1_match_analyses_get"];
        put?: never;
        /** Create Match Analysis */
        post: operations["create_match_analysis_api_v1_match_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match Analysis */
        get: operations["get_match_analysis_api_v1_match_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-analyses/{analysis_id}/resume-optimization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Resume Optimization */
        post: operations["create_resume_optimization_api_v1_match_analyses__analysis_id__resume_optimization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-analyses/{analysis_id}/cover-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Cover Letter */
        post: operations["create_cover_letter_api_v1_match_analyses__analysis_id__cover_letter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_v1_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List Models */
        post: operations["list_models_api_v1_llm_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyResumeSuggestionsRequest */
        ApplyResumeSuggestionsRequest: {
            /** Suggestions */
            suggestions: components["schemas"]["ResumeSuggestion"][];
        };
        /** Body_parse_resume_api_v1_profiles_parse_resume_post */
        Body_parse_resume_api_v1_profiles_parse_resume_post: {
            /** File */
            file: string;
        };
        /** CompanyBrief */
        CompanyBrief: {
            /** Company */
            company: string;
            /** Summary */
            summary: string;
            /** Culture Signals */
            culture_signals?: string[];
            /** Recent News */
            recent_news?: string[];
            /** Interview Signals */
            interview_signals?: string[];
            /** Red Flags */
            red_flags?: string[];
            /** Sources */
            sources?: components["schemas"]["SearchResult"][];
            /**
             * Researched At
             * Format: date-time
             */
            researched_at: string;
        };
        /** CoverLetterResult */
        CoverLetterResult: {
            /** Body */
            body: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "professional" | "warm" | "concise";
            /** Highlights Used */
            highlights_used?: string[];
            /** Critique Summary */
            critique_summary: string;
        };
        /** EducationEntry */
        EducationEntry: {
            /** Degree */
            degree: string;
            /** School */
            school: string;
            /** Duration */
            duration?: string | null;
            /** Highlights */
            highlights?: string[];
        };
        /** ExperienceEntry */
        ExperienceEntry: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Duration */
            duration?: string | null;
            /** Highlights */
            highlights?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreate */
        JobCreate: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Description */
            description: string;
            /** Location */
            location?: string | null;
            /** Url */
            url?: string | null;
            /** Source */
            source?: string | null;
            /** Raw Metadata */
            raw_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Profile Id */
            profile_id?: string | null;
        };
        /**
         * JobCreateRead
         * @description Job create response — includes queued match analysis when profile_id was sent.
         */
        JobCreateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Description */
            description: string;
            /** Location */
            location: string | null;
            /** Url */
            url: string | null;
            /** Source */
            source: string | null;
            /** Raw Metadata */
            raw_metadata: {
                [key: string]: unknown;
            } | null;
            company_brief?: components["schemas"]["CompanyBrief"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Match Analysis Id */
            match_analysis_id?: string | null;
        };
        /** JobExtraction */
        JobExtraction: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Description */
            description: string;
            /**
             * Match Summary
             * @description 1–2 sentence summary of the role for fast match screening.
             */
            match_summary: string;
            /** Work Mode */
            work_mode?: ("remote" | "hybrid" | "on-site" | "flexible") | null;
            /** Location */
            location?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /** Salary Range */
            salary_range?: string | null;
            /** Requirements */
            requirements?: string[];
        };
        /** JobParseRead */
        JobParseRead: {
            /** Job Text */
            job_text: string;
            structured_data: components["schemas"]["JobExtraction"];
        };
        /** JobParseRequest */
        JobParseRequest: {
            /** Text */
            text: string;
        };
        /** JobRead */
        JobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Description */
            description: string;
            /** Location */
            location: string | null;
            /** Url */
            url: string | null;
            /** Source */
            source: string | null;
            /** Raw Metadata */
            raw_metadata: {
                [key: string]: unknown;
            } | null;
            company_brief?: components["schemas"]["CompanyBrief"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobUpdate */
        JobUpdate: {
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Url */
            url?: string | null;
            /** Source */
            source?: string | null;
            /** Raw Metadata */
            raw_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** ListModelsRequest */
        ListModelsRequest: {
            /**
             * Llm Provider
             * @enum {string}
             */
            llm_provider: "openai" | "anthropic" | "google" | "groq" | "mistral" | "together" | "azure_openai" | "local";
            /** Llm Api Key */
            llm_api_key?: string | null;
            /** Llm Base Url */
            llm_base_url?: string | null;
            /**
             * Use Saved Credentials
             * @default false
             */
            use_saved_credentials: boolean;
        };
        /** MatchAnalysisCreate */
        MatchAnalysisCreate: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** MatchAnalysisRead */
        MatchAnalysisRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: components["schemas"]["MatchAnalysisStatus"] | string;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MatchAnalysisStatus
         * @enum {string}
         */
        MatchAnalysisStatus: "pending" | "completed" | "failed";
        /** ModelListRead */
        ModelListRead: {
            /** Models */
            models: string[];
        };
        /** ProfileCreate */
        ProfileCreate: {
            /** Name */
            name: string;
            /** Headline */
            headline?: string | null;
            /** Resume Text */
            resume_text: string;
            /** Structured Data */
            structured_data?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProfileRead */
        ProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Headline */
            headline: string | null;
            /** Resume Text */
            resume_text: string;
            /** Structured Data */
            structured_data: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Name */
            name?: string | null;
            /** Headline */
            headline?: string | null;
            /** Resume Text */
            resume_text?: string | null;
            /** Structured Data */
            structured_data?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProjectEntry */
        ProjectEntry: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Highlights */
            highlights?: string[];
        };
        /** ResumeExtraction */
        ResumeExtraction: {
            /** Name */
            name: string;
            /** Headline */
            headline?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["ExperienceEntry"][];
            /** Education */
            education?: components["schemas"]["EducationEntry"][];
            /** Projects */
            projects?: components["schemas"]["ProjectEntry"][];
        };
        /** ResumeOptimizationResult */
        ResumeOptimizationResult: {
            /** Summary */
            summary: string;
            /** Suggestions */
            suggestions?: components["schemas"]["ResumeSuggestion"][];
        };
        /** ResumeParseRead */
        ResumeParseRead: {
            /** Name */
            name?: string | null;
            /** Headline */
            headline?: string | null;
            /** Resume Text */
            resume_text: string;
            structured_data?: components["schemas"]["ResumeExtraction"] | null;
        };
        /** ResumeSuggestion */
        ResumeSuggestion: {
            /** Gap Evidence */
            gap_evidence: string;
            /**
             * Section
             * @enum {string}
             */
            section: "headline" | "skills" | "experience" | "projects";
            /**
             * Action
             * @enum {string}
             */
            action: "rewrite" | "add" | "emphasize";
            /** Target Label */
            target_label: string;
            /** Current Text */
            current_text?: string | null;
            /** Suggested Text */
            suggested_text: string;
            /** Rationale */
            rationale: string;
        };
        /** SearchResult */
        SearchResult: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Snippet */
            snippet: string;
        };
        /** SettingsRead */
        SettingsRead: {
            /** Llm Provider */
            llm_provider: ("openai" | "anthropic" | "google" | "groq" | "mistral" | "together" | "azure_openai" | "local") | null;
            /** Llm Model */
            llm_model: string | null;
            /** Llm Base Url */
            llm_base_url: string | null;
            /** Api Key Set */
            api_key_set: boolean;
            /** Configured */
            configured: boolean;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /**
             * Llm Provider
             * @enum {string}
             */
            llm_provider: "openai" | "anthropic" | "google" | "groq" | "mistral" | "together" | "azure_openai" | "local";
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Base Url */
            llm_base_url?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"][];
                };
            };
        };
    };
    create_profile_api_v1_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_resume_api_v1_profiles_parse_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_resume_api_v1_profiles_parse_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeParseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_v1_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_v1_profiles__profile_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_profile_resume_pdf_api_v1_profiles__profile_id__resume_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_resume_suggestions_api_v1_profiles__profile_id__apply_resume_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyResumeSuggestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"][];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_job_text_api_v1_jobs_parse_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobParseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_api_v1_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_research_api_v1_jobs__job_id__company_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyBrief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_match_analyses_api_v1_match_analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchAnalysisRead"][];
                };
            };
        };
    };
    create_match_analysis_api_v1_match_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchAnalysisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchAnalysisRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_analysis_api_v1_match_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchAnalysisRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resume_optimization_api_v1_match_analyses__analysis_id__resume_optimization_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeOptimizationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cover_letter_api_v1_match_analyses__analysis_id__cover_letter_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverLetterResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    update_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_llm_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListModelsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
